"""create_extracted_row

Revision ID: 6f678g761652
Revises: 5e567f650541
Create Date: 2026-08-29 12:58:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f678g761652'
down_revision: Union[str, None] = '5e567f650541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'extracted_rows',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_rows_file_id'), 'extracted_rows', ['file_id'], unique=False)
    op.create_index(op.f('ix_extracted_rows_row_number'), 'extracted_rows', ['row_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_rows_row_number'), table_name='extracted_rows')
    op.drop_index(op.f('ix_extracted_rows_file_id'), table_name='extracted_rows')
    op.drop_table('extracted_rows')
    # ### end Alembic commands ###
