"""create_normalized_facts

Revision ID: 7g789h872763
Revises: 6f678g761652
Create Date: 2026-08-29 14:07:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7g789h872763'
down_revision: Union[str, None] = '6f678g761652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'normalized_facts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('extracted_row_id', sa.Uuid(), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('canonical_name', sa.String(), nullable=False),
        sa.Column('value_numeric', sa.Numeric(), nullable=True),
        sa.Column('value_string', sa.String(), nullable=True),
        sa.Column('date_value', sa.Date(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['extracted_row_id'], ['extracted_rows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_facts_canonical_name'), 'normalized_facts', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_normalized_facts_category'), 'normalized_facts', ['category'], unique=False)
    op.create_index(op.f('ix_normalized_facts_date_value'), 'normalized_facts', ['date_value'], unique=False)
    op.create_index(op.f('ix_normalized_facts_extracted_row_id'), 'normalized_facts', ['extracted_row_id'], unique=False)
    op.create_index(op.f('ix_normalized_facts_file_id'), 'normalized_facts', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_facts_file_id'), table_name='normalized_facts')
    op.drop_index(op.f('ix_normalized_facts_extracted_row_id'), table_name='normalized_facts')
    op.drop_index(op.f('ix_normalized_facts_date_value'), table_name='normalized_facts')
    op.drop_index(op.f('ix_normalized_facts_category'), table_name='normalized_facts')
    op.drop_index(op.f('ix_normalized_facts_canonical_name'), table_name='normalized_facts')
    op.drop_table('normalized_facts')
    # ### end Alembic commands ###
